TVTracker/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import HomePageView
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",HomePageView.as_view(), name="home"),
    path("search/",include("search_movies.urls", namespace="search_movies")),
    path("movie/",include("movie_details.urls", namespace="movie_details")),
    path("user/", include("user_auth.urls", namespace="user_auth")),
    path("profile/",include("user_profile.urls", namespace="user_profile"))
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

movie_details/urls.py
from django.urls import path
from . import views

app_name = 'movie_details'
urlpatterns = [
    path("<imdb_id>", views.get_movie_details, name='movie-details'),
    path("<imdb_id>/addmovietowatching", views.add_movies_watching, name = "add-movie-to-watching"),
    path("<imdb_id>/addmovietocompleted", views.add_movies_completed, name = "add-movie-to-completed"),
    path("<imdb_id>/addmovietoplanned", views.add_movies_planned, name = "add-movie-to-planned")
]

search_movies/urls.py
from django.urls import path
from . import views

app_name = 'search_movies'

urlpatterns = [
    path("", views.search_results, name="search_results"),
]

user_auth/urls.py
from django.urls import path
from . import views

app_name = 'user_auth'

urlpatterns = [
    path("register", views.create_new_user, name="register"),
    path("login",views.login_user, name="login"),
    path("logout",views.logout_user, name = "logout")
]

user_profile/urls.py
from django.urls import path
from . import views

app_name = 'user_profile'

urlpatterns = [
    path("<username>", views.get_user_profile, name="profile"),
]

movie_details/models.py
from django.db import models

# Create your models here.
class Movie(models.Model):
    Title = models.CharField(max_length=255)
    Year = models.CharField(max_length=25, blank=True)
    Rated = models.CharField(max_length=10,blank=True)
    Genre = models.CharField(max_length=255, blank=True)
    Director = models.CharField(max_length=100, blank=True)
    Actors = models.CharField(max_length=255, blank=True)
    Plot = models.CharField(max_length=900, blank=True)
    imdbID = models.CharField(max_length=10, blank=True)
    Type = models.CharField(max_length=10, blank=True)

    class Meta:
        verbose_name_plural = "movies"

    def __str__(self) -> str:
        return self.Title

movie_details/views.py
from django.shortcuts import render
from .models import Movie
from user_profile.models import Profile
import environ
import requests
from django.template import loader
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse

env = environ.Env()
# reading .env file
environ.Env.read_env()

API_KEY = env("API_KEY")
# Create your views here.

def get_movie_details(request, imdb_id):
    if Movie.objects.filter(imdbID = imdb_id).exists():
        movie_data = Movie.objects.get(imdbID = imdb_id)
        db_cache = True

        
    else:
        url = 'http://www.omdbapi.com/?apikey='+API_KEY+'&i=' + imdb_id
        response = requests.get(url)
        movie_data = response.json()

        if movie_data['Type'] == 'movie':
            m, created = Movie.objects.get_or_create(
                Title = movie_data['Title'],
                Year = movie_data['Year'],
                Rated = movie_data['Rated'],
                Genre = movie_data['Genre'],
                Director = movie_data['Director'],
                Actors = movie_data['Actors'],
                Plot = movie_data['Plot'],
                imdbID = movie_data['imdbID'],
            )
            m.save()
        db_cache = False
    
    context = {
            'movie_data' : movie_data,
            'db_cache' : db_cache
        }
    template = loader.get_template('movie_details.html')

    return HttpResponse(template.render(context, request))

def add_movies_planned(request, imdb_id):
    movie = Movie.objects.get(imdbID = imdb_id)
    user = request.user
    profile = Profile.objects.get(user = user)
    
    profile.planned_movies.add(movie)

    return HttpResponseRedirect(reverse('movie_details:movie-details', args = [imdb_id]))

def add_movies_watching(request, imdb_id):
    movie = Movie.objects.get(imdbID = imdb_id)
    user = request.user
    profile = Profile.objects.get(user = user)

    if profile.planned_movies.filter(imdbID = imdb_id).exists():
        profile.planned_movies.remove(movie)

    profile.watching_movies.add(movie)

    return HttpResponseRedirect(reverse('movie_details:movie-details', args = [imdb_id]))

def add_movies_completed(request, imdb_id):
    movie = Movie.objects.get(imdbID = imdb_id)
    user = request.user
    profile = Profile.objects.get(user = user)

    if profile.watching_movies.filter(imdbID = imdb_id).exists():
        profile.watching_movies.remove(movie)
    
    if profile.planned_movies.filter(imdbID = imdb_id).exists():
        profile.planned_movies.remove(movie)

    profile.completed_movies.add(movie)

    return HttpResponseRedirect(reverse('movie_details:movie-details', args = [imdb_id]))

templates/base.html
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale = 1">
        <title>TV Tracker</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
    </head>
    <body>
        <script src = "https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
        <nav class = "navbar navbar-expand-lg bg-body-tertiary">
            <div class = "container-fluid">
                <a class = "navbar-brand" href="{% url 'home' %}">TV Tracker</a>
            
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                        {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{% url 'user_profile:profile' user.username%}">Hi {{user}}</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{% url 'user_auth:logout' %}">Logout</a>
                        </li>
                        {% else %}
                        <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'user_auth:login' %}">Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{% url 'user_auth:register' %}">Signup</a>
                        </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>  
        {% block content %}
        {% endblock %} 
    </body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block content %}
<h1>TV Tracker</h1>

<div>
    <span>Hi {{request.user}}</span> 
    <br>
    <span><a href = "{% url 'user_auth:logout' %}">Logout</a></span>
    <br>
    <a href = "{% url 'user_profile:profile' user.username%}">Profile</a>
</div>
<br><br>
<form action = "{% url 'search_movies:search_results' %}" method="get">
    <input name="q" type="text" placeholder="Search for a movie">
    <input type="submit" value="Submit">
</form>

{% endblock %}

templates/movie_details.html
{% extends 'base.html' %}

{% block content %}
<h1>
    Movie details for : {{ movie_data.Title }}
</h1>

<ul>
    <li>Title : {{ movie_data.Title }}</li>
    <li>Year : {{ movie_data.Year }}</li>
    <li>Rated : {{ movie_data.Rated }}</li>
    <li>Genre : {{ movie_data.Genre }}</li>
    <li>Director : {{ movie_data.Director }}</li>
    <li>Actors : {{ movie_data.Actors }}</li>
    <li>Plot : {{ movie_data.Plot }}</li>
</ul>

<a href="{% url 'movie_details:add-movie-to-planned' movie_data.imdbID %}">Add to planned</a>
<a href="{% url 'movie_details:add-movie-to-watching' movie_data.imdbID %}">Add to watching</a>
<a href="{% url 'movie_details:add-movie-to-completed' movie_data.imdbID %}">Add to completed</a>

{% endblock %}

templates/profile.html
{% extends 'base.html' %}

{% block content %}

    <div>
        {% if profile.profile_pic %}
            <img src = "{{ profile.profile_pic.url }}">
        {% else %}
            <img src = "">
        {% endif %}
        <span><b>{{ profile.user.username }}</b></span>
    </div>

    <div>
        <ul>
            <li><h5>User Information</h5></li>
            <li>Joined on : {{ profile.date_created }}</li>
        </ul>
    </div>

    <div>
        <h4> Movies</h4>
        <ul>
            <li>Watching : {{ movies_watching_count }}</li>
            <li>Completed : {{ movies_completed_count }}</li>
            <li>Planned : {{ movies_planned_count }}</li>
        </ul>
    </div>

{% endblock %}

templates/search_results.html
{% extends 'base.html' %}

{% block content %}
<h2>
    Search Results for : 
    <h3>{{query}}</h3>
</h2>



<ul>
    {% for movie in movie_data.Search %}
        <li>
            <a href = "{% url 'movie_details:movie-details' movie.imdbID %}">Title : {{movie.Title}} </a>
            <br>Year : {{movie.Year}}
        </li>
    {% endfor %}
</ul>

{% endblock %}